name: 'Activate FDR4 license'
description: 'Provides the facility to activate FDR4 license via parameters.'
inputs:
  license-type:
    description: 'License type, with 2 for academic'
    required: false
    default: 2
  name:
    description: 'Name for the license'
    required: true
    default: 'Anonymous'
  email:
    description: 'E-mail address for the license'
    required: true
    default: 'anonymous@github.com'
runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH}/get_license.sh ${{ inputs.license-type }} ${{ inputs.email }} \"${{ inputs.name }}\"
      shell: bash
